version: 1.0.{build}
clone_depth: 1
environment:
  JSPM_GITHUB_AUTH_TOKEN:
    secure: 9999
install:
- npm install
- node_modules\.bin\jspm config registries.bower.handler jspm-bower-endpoint
- node_modules\.bin\jspm config registries.bower.timeouts.lookup 300
- node_modules\.bin\jspm config registries.bower.timeouts.build 300
- node_modules\.bin\jspm config registries.github.timeouts.lookup 300
- node_modules\.bin\jspm config registries.github.timeouts.build 300
- node_modules\.bin\jspm config registries.github.auth %JSPM_GITHUB_AUTH_TOKEN%
- node_modules\.bin\jspm config registries.npm.timeouts.lookup 300
- node_modules\.bin\jspm config registries.npm.timeouts.build 300
- node_modules\.bin\jspm install
cache:
- node_modules -> package.json
- jspm_packages -> package.json
artifacts:
- path: dist
deploy:
- provider: WebDeploy
  server: https://zzz.com/msdeploy.axd?site=zzzProfile
  website: zzzProfile
  username: user1
  password:
    secure: user1_123
  artifact: dist.zip
